name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        id: setupJava
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: cactuslab/maven-toolchains-xml-action@v1
        with:
          toolchains: |
            [
              {"jdkVersion": "17", "jdkHome": "${{steps.setupJava.outputs.path}}"}
            ]
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn --batch-mode test javadoc:aggregate
